/** helper.sh 生成（纯函数，TDD：test/helper.test.ts）。
 *  通知 action 在干净环境（dash -c、PATH 丢失）执行 → 一律绝对路径。
 *  回复经 printf '%s' 写入文件（防注入）。终结后的状态反馈由扩展侧
 *  用同 id 重新 notify 替换完成（部分设备 remove 无效，替换是可靠通道）。 */

export interface HelperScriptOptions {
  repliesDir: string;
  /** Termux shell 绝对路径（shebang） */
  shBin: string;
}

export function buildHelperScript(opts: HelperScriptOptions): string {
  return [
    `#!${opts.shBin}`,
    "# pi-notify-termux reply bridge (generated by extension; do not edit)",
    `replies_dir="${opts.repliesDir}"`,
    'case "$1" in',
    "  notify)",
    '    ts="$2"; text="$3"',
    '    printf \'%s\' "$text" > "$replies_dir/notify-${ts}.reply"',
    "    ;;",
    "  ask)",
    '    id="$2"; text="$3"',
    '    printf \'%s\' "$text" > "$replies_dir/ask-${id}.reply"',
    "    ;;",
    "  cancel)",
    '    id="$2"',
    '    : > "$replies_dir/ask-${id}.cancel"',
    "    ;;",
    "esac",
    "",
  ].join("\n");
}
