/** helper.sh 生成（纯函数，TDD：test/helper.test.ts）。
 *  通知 action 在干净环境（dash -c、PATH 丢失）执行 → 一律绝对路径。
 *  回复经 printf '%s' 写入文件（防注入）；写完顺带 termux-notification-remove
 *  移除本条通知（Android 点按钮后不会自动消失，需主动 cancel）。 */

export interface HelperScriptOptions {
  repliesDir: string;
  /** Termux shell 绝对路径（shebang） */
  shBin: string;
  /** termux-notification-remove 绝对路径 */
  removeBin: string;
  /** 需求 1 结果通知的固定 id（回复后移除） */
  resultId: string;
}

export function buildHelperScript(opts: HelperScriptOptions): string {
  return [
    `#!${opts.shBin}`,
    "# pi-notify-termux reply bridge (generated by extension; do not edit)",
    `replies_dir="${opts.repliesDir}"`,
    'case "$1" in',
    "  notify)",
    '    ts="$2"; text="$3"',
    '    printf \'%s\' "$text" > "$replies_dir/notify-${ts}.reply"',
    `    "${opts.removeBin}" --id "${opts.resultId}"`,
    "    ;;",
    "  ask)",
    '    id="$2"; text="$3"',
    '    printf \'%s\' "$text" > "$replies_dir/ask-${id}.reply"',
    `    "${opts.removeBin}" --id "ask-\${id}"`,
    "    ;;",
    "  cancel)",
    '    id="$2"',
    '    : > "$replies_dir/ask-${id}.cancel"',
    "    ;;",
    "esac",
    "",
  ].join("\n");
}
